### ISSUE TITLE
Does this plugin not support version 4.x?

### ISSUE THREAD

**Issue by me66ccff** [naiiveprojects/nv.gd.file_system#1]
Does this plugin not support version 4.x?

行 1:Unexpected "Identifier" in class body.
行 2:Unexpected "extends" in class body.
行 36:"yield" was removed in Godot 4. Use "await" instead.
行 36:Expected statement, found "(" instead.
行 98:"yield" was removed in Godot 4. Use "await" instead.
行 98:Expected statement, found "(" instead.
行 109:"yield" was removed in Godot 4. Use "await" instead.
行 109:Expected statement, found "(" instead.
行 125:"yield" was removed in Godot 4. Use "await" instead.
行 125:Expected statement, found "(" instead.

**Comment by illlustr** [comment]
what a coincident, just port it couple hour ago [here](https://github.com/naiiveprojects/nv.gd.file_system/tree/4.x), Let me know if you encounter any problems
