### ISSUE TITLE
unresponsive FileSystem SplitContainer when switching

### ISSUE THREAD

**Issue by mcdz** [naiiveprojects/nv.gd.file_system#14]
Alt + S or Project > Tool > ! switching the docs removes split bar drag control from the side docked FileSystem.

**Comment by illlustr** [comment]
thank you for the report
currently i cannot find a way to fix this, the quick fix might be removing line 214 & 215

![image](https://github.com/naiiveprojects/nv.gd.file_system/assets/51869044/edbd4c01-58aa-4bdc-b917-647b3e5de535)

but without that line the editor will throw an error : `scene/main/node.cpp:2778 - Condition "p_node->data.parent" is true.`  every time the filesystem move to the bottom dock, this error will not affect anything (as far as i know), but it could cause confusion because there is no explanation of where the error comes from. i will try to dig bit deeper in to this later

**Comment by mcdz** [comment]
I experimented with your plugin as well, tried to just show hide the sidebar, by not opening the file manager automatically from bottom bar.
but that bug remained.
maybe engine related.
thanks for sharing the temp fix.

Thanks for contributing to Godot Engine. <3

**Comment by mcdz** [comment]
![image](https://github.com/naiiveprojects/nv.gd.file_system/assets/25784180/cd7fea42-31f0-492a-a170-f0bc010b5eea)
additionally causes this issue.

**Comment by mcdz** [comment]
It's really amazing that you added shortcut to plugin. natively it isn't a feature I guess.

**Comment by illlustr** [comment]
> ![image](https://private-user-images.githubusercontent.com/25784180/338543188-cd7fea42-31f0-492a-a170-f0bc010b5eea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxODE4NTEsIm5iZiI6MTcxODE4MTU1MSwicGF0aCI6Ii8yNTc4NDE4MC8zMzg1NDMxODgtY2Q3ZmVhNDItMzFmMC00OTJhLWExNzAtZjBiYzAxMGI1ZWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDA4MzkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5Mjc0OTUxNzZhNTNlMDNkYjA4Njc4OTVmZjFmZDQ5NTAzNzE0ODFhMzNiODViYzdhMTY5NDliZmRiODY2MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i7UdKTh7glGMfYrNwQX8tcDvP2QM3joGR-ZZWxYkSgY) additionally causes this issue.

found out we actualy just need to remove line 215, since only the split container that causing original issue, it will fix the issue above xd

**Comment by illlustr** [comment]
> It's really amazing that you added shortcut to plugin. natively it isn't a feature I guess.

it is kinda a feature i think, since godot editor itself is build on top of the engine using the same node system, for the most part we can extend/modifying it the same way we modify godot project 😊

**Comment by illlustr** [comment]
i think this issue fixed in https://github.com/naiiveprojects/nv.gd.file_system/commit/4d95494a83b9c2f5292c20301bb4d0408dfcb579, let me know if you still encounter this issue, i will try to update assetlib tomorrow
