### ISSUE TITLE
4.2 beta2 Unable to use due to error reporting

### ISSUE THREAD

**Issue by NetCodersX** [naiiveprojects/nv.gd.file_system#7]
error message：
  res://addons/nv.file_system/nv.file_system.gd:72 - Trying to assign value of type 'SplitContainer' to a variable of type 'VSplitContainer'.
  res://addons/nv.file_system/nv.file_system.gd:165 - Invalid set index 'button_pressed' (on base: 'Nil') with value of type 'bool'.

**Comment by MoNouri97** [comment]
I fixed this simply by changing  line 25
`var file_system_vsplit: VSplitContainer` to `var file_system_vsplit: SplitContainer`

**Comment by illlustr** [comment]
fixed https://github.com/naiiveprojects/nv.gd.file_system/commit/7d5ccb7f067da5f15fe818fd747db7d8945b52b1 , thanks to @MoNouri97
