### ISSUE TITLE
Update asset library to latest version (3.x)

### ISSUE THREAD

**Issue by mark-rafter** [naiiveprojects/nv.gd.file_system#9]
The version on the asset library still has the bug resolved in PR #4

**Comment by illlustr** [comment]
waiting for review, hopefully the database is fixed now 🙏
![image](https://github.com/naiiveprojects/nv.gd.file_system/assets/51869044/d203964b-d50d-45c9-9707-7b005eadc5a6)
![image](https://github.com/naiiveprojects/nv.gd.file_system/assets/51869044/9a862250-f49f-4cae-b817-47ffa7d75f7e)

**Comment by illlustr** [comment]
[its up](https://godotengine.org/asset-library/asset/2223) 🎉, it also will remember last dock position now #10
